---
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    pandoc_args: [
      "--listings"
    ]
fontsize: 11pt
tables: true
preamble:
- \usepackage{xcolor}

title: "Title of this Document"
subtitle: "A Subtitle that may Flow onto Additional Space if Necessary"
author:
- name: Author One
  affiliation: Institute
  description: Title
  email: email@ku.edu
- name:  Author Two 
  affiliation: Institute
  description: Title
  email: email@ku.edu
---

```{r setup, include=FALSE}
##This Invisible Chunk is required in all CRMDA documents
tmpdir <- paste0("tmpout")
if (!dir.exists(tmpdir)) dir.create(tmpdir, recursive = TRUE)
knitr::opts_chunk$set(echo=TRUE, comment=NA, fig.path=paste0(tmpdir, "/p-"))
options(width = 70)
```

\begin{abstract}
Please include abstract here
\end{abstract}


# Nuts and Bolts

## Make minimal changes to the top part.

Fill in your name, title, email, tags.  Please don't change the
pdf_document settings unless you know what you are doing.


# LaTeX Syntax is allowed

\[
\Sigma_{gt}=\Lambda_{gt}\Psi_{gt}\Lambda'_{gt}+\Theta_{gt}
\]

# `R` code chunks 

```{r ex-1, results='asis', echo=TRUE}
set.seed(1234)
x <- rnorm(100, 0, 1)
y <- rnorm(100, 0, 1)
library(xtable)
print(xtable(head(data.frame(x, y))), comment=FALSE)
```

